# Generated by Django 5.2.15 on 2026-06-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.state')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='requests.request')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.state')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.transition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
