# Generated by Django 5.2.15 on 2026-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فرم')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('fields_schema', models.JSONField(default=list, verbose_name='ساختار فیلدها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تعریف فرم',
                'verbose_name_plural': 'تعریف فرم\u200cها',
            },
        ),
    ]
