# Generated by Django 5.2.15 on 2026-06-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام وضعیت')),
                ('code', models.SlugField(max_length=100, verbose_name='کد وضعیت')),
                ('is_initial', models.BooleanField(default=False, verbose_name='وضعیت شروع')),
                ('is_final', models.BooleanField(default=False, verbose_name='وضعیت نهایی')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام گردش کار')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='کد سیستم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام عملیات')),
                ('assignment_type', models.CharField(choices=[('DIRECT_MANAGER', 'مدیر مستقیم درخواست\u200cکننده'), ('SPECIFIC_USER', 'کاربر مشخص'), ('ROLE', 'نقش سیستمی (مثلاً مدیر مالی)'), ('CREATOR', 'خود درخواست\u200cکننده')], default='DIRECT_MANAGER', max_length=50)),
                ('assignment_data', models.CharField(blank=True, help_text='ID کاربر یا کد نقش', max_length=255, null=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transitions', to='workflow.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transitions', to='workflow.state')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('workflow', 'code')},
        ),
    ]
