# Generated by Django 5.2.15 on 2026-06-25 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='توضیحات/هامش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('from_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.state', verbose_name='وضعیت قبلی')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='requests.request')),
                ('to_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.state', verbose_name='وضعیت جدید')),
                ('transition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.transition', verbose_name='عملیات')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام دهنده')),
            ],
            options={
                'verbose_name': 'لاگ عملیات',
                'verbose_name_plural': 'لاگ\u200cهای عملیات',
                'ordering': ['-created_at'],
            },
        ),
    ]
