# Generated by Django 5.2.15 on 2026-06-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'نوع سند',
                'verbose_name_plural': 'انواع سند',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='موضوع')),
                ('content', models.TextField(verbose_name='متن نامه')),
                ('indicator_number', models.CharField(max_length=100, unique=True, verbose_name='شماره اندیکاتور')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('urgent', 'فوری'), ('immediate', 'آنی')], default='normal', max_length=20, verbose_name='فوریت')),
                ('classification', models.CharField(choices=[('public', 'عادی'), ('confidential', 'محرمانه'), ('secret', 'سری')], default='public', max_length=20, verbose_name='طبقه\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='correspondence.documenttype', verbose_name='نوع سند')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_letters', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='correspondence.letter', verbose_name='نامه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'گیرنده نامه',
                'verbose_name_plural': 'گیرندگان نامه',
                'unique_together': {('letter', 'user')},
            },
        ),
    ]
